sudo: required
dist: xenial
language: python
python:
  - '3.5'
install:
 - pip install --quiet -r ci/requirements.txt
 - git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
 - git clone https://github.com/QubesOS/qubes-core-admin-client ~/core-admin-client
script:
 - PYTHONPATH=~/core-admin-client python3 -m pylint --rcfile=.pylintrc qui
 - ~/qubes-builder/scripts/travis-build
env:
 - DIST_DOM0=fc25 USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1

# don't build tags which are meant for code signing only
branches:
  except:
    - /.*_.*/
    - build
